<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<form class="form" data-mage-init='{"validation": {}}' action="<?php echo $block->getUrl()."custom/order/post"; ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off" data-hasrequired="* Required Fields">
    <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend"><span>Custom Order Form</span></legend><br>
        <input type="hidden" name="success_url" value="">
        <input type="hidden" name="error_url" value="">
        
        <div class="field required">
            <label class="label" for="orde_id">
                <span>Order Id</span>
            </label>

            <div class="control">
                <input type="text" id="orde_id" name="orde_id" value="" title="Order Id" class="input-text required-entry" data-validate="{required:true, 'validate-number':true}" aria-required="true">
            </div>
        </div>

        <div class="field required">
            <label for="recommend" class="label">
                <span>Recommend</span>
            </label>
            <div class="control">
                <input type="text" name="recommend" id="recommend" value="" title="Recommend" class="input-text" data-validate="{required:true}" aria-required="true">
            </div>
        </div>

    </fieldset>
    <div class="actions-toolbar">
        <input type="hidden" name="hideit" id="hideit" value="" />
        <div class="primary">
            <button type="submit" class="action submit primary" title="Submit"><span>Submit</span></button>
        </div>
    </div>
</form>